In [1]:
mydict = {"fruit_name":("apple","mango", "orange")}

In [2]:
mydict.keys()

dict_keys(['fruit_name'])

In [4]:
mydict.values()

dict_values([('apple', 'mango', 'orange')])

In [1]:
class human:
    name = None
    age = None
    def get_name(self):
        print("enter you name")
        self.name = input()
    def get_age(self):
        print("enter you age")
        self.age = input()
    def print_name(self):
        print("your name is", self.name)
    def print_age(self):
        print("your name is", self.age)

In [2]:
human1 = human()

In [3]:
human1.get_name()

enter you name
ruchir


In [5]:
human1.get_age()

enter you age
32


In [7]:
human1.print_name()

your name is ruchir


In [8]:
human1.print_age()

your name is 32


In [9]:
class student:
    def __init__(self, name, age, branch):
        self.name = name
        self.age = age
        self.branch = branch
    def print_students(self):
        print('name', self.name)
        print('age', self.age)
        print('branch', self.branch)


In [10]:
s1 = student()

TypeError: __init__() missing 3 required positional arguments: 'name', 'age', and 'branch'

In [11]:
s1 = student('bob', '32', 'political science')

In [12]:
s1

In [13]:
s1.print_students()

name bob
age 32
branch political science


In [17]:
class fruit:
    def __init__(self):
        print("I am the base fruit class")

class citrus(fruit):
    def __init__(self):
        super().__init__()
        print("I am a citrus fruit of the inherited class")

In [18]:
c1 = citrus()

I am the base fruit class
I am a citrus fruit of the inherited class


In [19]:
c1

In [21]:
import numpy as np

In [22]:
a = np.array([1,2,3])

In [23]:
a

array([1, 2, 3])

In [25]:
b = np.array([[1,2,3],[4,5,6]])

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
c = np.zeros([5,5])

In [29]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
sum = np.sum((a,b), axis = 0)

In [32]:
sum

array([[2, 4, 6],
       [5, 7, 9]])

In [36]:
np.sum(b, axis = 1)

array([ 6, 15])

In [37]:
x = np.array([12,43,2,100,54,5,68])

In [38]:
x

array([ 12,  43,   2, 100,  54,   5,  68])

In [39]:
np.argsort(x)

array([2, 5, 0, 1, 4, 6, 3])

In [40]:
np.argsort(x)[-2:]

array([6, 3])

In [41]:
np.argsort(x)[-2:][::-1]

array([3, 6])

In [42]:
sorted_x = np.argsort(x)[-2:][::-1]

In [43]:
sorted_x

array([3, 6])

In [44]:
sorted_x = [np.argsort(x)[-2:][::-1]]

In [45]:
sorted_x

[array([3, 6])]

In [46]:
new_x[np.argsort(x)[-2:][::-1]]

NameError: name 'new_x' is not defined

In [47]:
sorted_x[np.argsort(x)[-2:][::-1]]

TypeError: only integer scalar arrays can be converted to a scalar index

In [48]:
x[np.argsort(x)[-2:][::-1]]

array([100,  68])

In [49]:
x

array([ 12,  43,   2, 100,  54,   5,  68])

In [50]:
sorted_x = x[np.argsort(x)[-2:][::-1]]

In [51]:
sorted_x

array([100,  68])

In [53]:
import pandas as pd

In [54]:
l1 = [1,2,3,4,5]
data1 = pd.DataFrame(l1)

In [55]:
data1

0
0  1
1  2
2  3
3  4
4  5

In [56]:
dt1 = {"fruit_name":["apple","mango","orange"], "count":[10,20,30]}

In [57]:
data2 = pd.DataFrame(dt1)

In [58]:
data2

fruit_name  count
0      apple     10
1      mango     20
2     orange     30

In [59]:
#find the first recurring character

In [60]:
string = "ABCDA"

In [62]:
for s in string:
    print(s)

A
B
C
D
A


In [63]:
for s in string:
    if s == 'A':
        print(s)

A
A


In [64]:
for s in string:
    if s == 'A' or 'B' or 'C':
        print(s)

A
B
C
D
A


In [65]:
for s in string:
    if s == 'A' or s == 'B' or s == 'C':
        print(s)

A
B
C
A


In [67]:
count = set()
for s in string:
    if s in count:
        print(s)
    else:
        count.add(s)

A


In [69]:
!python ReturnfirstRecurringCharacter.py

Traceback (most recent call last):
  File "ReturnfirstRecurringCharacter.py", line 19, in <module>
    recur_charac(string=sys.argv[1])
IndexError: list index out of range


In [71]:
!python ReturnfirstRecurringCharacter.py ABCDDA

D
