In [1]:
mydict = {"fruit_name":("apple","mango", "orange")}

In [2]:
mydict.keys()

dict_keys(['fruit_name'])

In [4]:
mydict.values()

dict_values([('apple', 'mango', 'orange')])

In [1]:
class human:
    name = None
    age = None
    def get_name(self):
        print("enter you name")
        self.name = input()
    def get_age(self):
        print("enter you age")
        self.age = input()
    def print_name(self):
        print("your name is", self.name)
    def print_age(self):
        print("your name is", self.age)

In [2]:
human1 = human()

In [3]:
human1.get_name()

enter you name
ruchir


In [5]:
human1.get_age()

enter you age
32


In [7]:
human1.print_name()

your name is ruchir


In [8]:
human1.print_age()

your name is 32


In [9]:
class student:
    def __init__(self, name, age, branch):
        self.name = name
        self.age = age
        self.branch = branch
    def print_students(self):
        print('name', self.name)
        print('age', self.age)
        print('branch', self.branch)


In [10]:
s1 = student()

TypeError: __init__() missing 3 required positional arguments: 'name', 'age', and 'branch'

In [11]:
s1 = student('bob', '32', 'political science')

In [12]:
s1

In [13]:
s1.print_students()

name bob
age 32
branch political science


In [17]:
class fruit:
    def __init__(self):
        print("I am the base fruit class")

class citrus(fruit):
    def __init__(self):
        super().__init__()
        print("I am a citrus fruit of the inherited class")

In [18]:
c1 = citrus()

I am the base fruit class
I am a citrus fruit of the inherited class


In [19]:
c1

In [21]:
import numpy as np

In [22]:
a = np.array([1,2,3])

In [23]:
a

array([1, 2, 3])

In [25]:
b = np.array([[1,2,3],[4,5,6]])

In [26]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
c = np.zeros([5,5])

In [29]:
c

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
sum = np.sum((a,b), axis = 0)

In [32]:
sum

array([[2, 4, 6],
       [5, 7, 9]])

In [36]:
np.sum(b, axis = 1)

array([ 6, 15])

In [37]:
x = np.array([12,43,2,100,54,5,68])

In [38]:
x

array([ 12,  43,   2, 100,  54,   5,  68])

In [39]:
np.argsort(x)

array([2, 5, 0, 1, 4, 6, 3])

In [40]:
np.argsort(x)[-2:]

array([6, 3])

In [41]:
np.argsort(x)[-2:][::-1]

array([3, 6])

In [42]:
sorted_x = np.argsort(x)[-2:][::-1]

In [43]:
sorted_x

array([3, 6])

In [44]:
sorted_x = [np.argsort(x)[-2:][::-1]]

In [45]:
sorted_x

[array([3, 6])]

In [46]:
new_x[np.argsort(x)[-2:][::-1]]

NameError: name 'new_x' is not defined

In [47]:
sorted_x[np.argsort(x)[-2:][::-1]]

TypeError: only integer scalar arrays can be converted to a scalar index

In [48]:
x[np.argsort(x)[-2:][::-1]]

array([100,  68])

In [49]:
x

array([ 12,  43,   2, 100,  54,   5,  68])

In [50]:
sorted_x = x[np.argsort(x)[-2:][::-1]]

In [51]:
sorted_x

array([100,  68])

In [53]:
import pandas as pd

In [54]:
l1 = [1,2,3,4,5]
data1 = pd.DataFrame(l1)

In [55]:
data1

0
0  1
1  2
2  3
3  4
4  5

In [56]:
dt1 = {"fruit_name":["apple","mango","orange"], "count":[10,20,30]}

In [57]:
data2 = pd.DataFrame(dt1)

In [58]:
data2

fruit_name  count
0      apple     10
1      mango     20
2     orange     30

In [59]:
#find the first recurring character

In [60]:
string = "ABCDA"

In [62]:
for s in string:
    print(s)

A
B
C
D
A


In [63]:
for s in string:
    if s == 'A':
        print(s)

A
A


In [64]:
for s in string:
    if s == 'A' or 'B' or 'C':
        print(s)

A
B
C
D
A


In [65]:
for s in string:
    if s == 'A' or s == 'B' or s == 'C':
        print(s)

A
B
C
A


In [67]:
count = set()
for s in string:
    if s in count:
        print(s)
    else:
        count.add(s)

A


In [69]:
!python ReturnfirstRecurringCharacter.py

Traceback (most recent call last):
  File "ReturnfirstRecurringCharacter.py", line 19, in <module>
    recur_charac(string=sys.argv[1])
IndexError: list index out of range


In [71]:
!python ReturnfirstRecurringCharacter.py ABCDDA

D


In [73]:
!python ReturnfirstRecurringCharacter.py ABBCDDA

B


In [79]:
cdict = {}
for s in string:
    cdict.update(s = 1)
    print(s)

A
B
C
D
A


In [80]:
cdict

{'s': 1}

In [81]:
cdict = {}
for s in string:
    cdict[s] = 1

In [82]:
cdict

{'A': 1, 'B': 1, 'C': 1, 'D': 1}

In [83]:
!python ReturnfirstRecurringCharacter.py ABCDDA

In [84]:
!python ReturnfirstRecurringCharacter.py ABCDDA

D


In [85]:
!python ReturnfirstRecurringCharacter.py ABBCDDA

B


In [86]:
!python ReturnfirstRecurringCharacter.py ABCD

None


In [87]:
33 % 25

8

In [88]:
53 % 25

3

In [89]:
20 % 25

20

In [92]:
x = int(3/2)

In [93]:
x

1

In [94]:
!python CoinChange.py 33

Traceback (most recent call last):
  File "CoinChange.py", line 24, in <module>
    print(num_coins(cents=sys.argv[1]))
  File "CoinChange.py", line 16, in num_coins
    coin_number += int(cents/coin)
TypeError: unsupported operand type(s) for /: 'str' and 'int'


In [95]:
!python CoinChange.py 33

5


In [96]:
p = int(8/10)

In [97]:
p

0

In [98]:
8 % 10

8

In [99]:
3 % 1

0

In [100]:
dic = {'a': 5 ,'b':3,'c':1}

In [101]:
dic

{'a': 5, 'b': 3, 'c': 1}

In [110]:
print(sorted(dic.values()))

[1, 3, 5]


In [107]:
sdic = sorted(dic.values())

In [108]:
sdic

[1, 3, 5]

In [111]:
31 % 1

0

In [112]:
31 % 10

1

In [113]:
31 % 25

6

In [114]:
35 % 25

10

In [115]:
!python CoinChange.py 33

5
Traceback (most recent call last):
  File "CoinChange.py", line 43, in <module>
    print(min_coins(cents=int(sys.argv[1])))
  File "CoinChange.py", line 32, in min_coins
    mod_10 = cent % 10
NameError: global name 'cent' is not defined


In [116]:
!python CoinChange.py 33

5
None


In [117]:
!python CoinChange.py 33

5
9


In [118]:
!python CoinChange.py 31

3
7


In [119]:
!python CoinChange.py 33

  File "CoinChange.py", line 46
    print(f"greedy={greedy} and mini = {mini}")
                                             ^
SyntaxError: invalid syntax


In [120]:
!python CoinChange.py 33

greedy= {greedy} and mini = {mini}


In [121]:
!python CoinChange.py 33

  File "CoinChange.py", line 46
    print(f'greedy= {greedy} and mini = {mini}')
                                              ^
SyntaxError: invalid syntax


In [122]:
!python CoinChange.py 33

('greedy=', 5, 'and mini =', 9)


In [123]:
!python CoinChange.py 33

('greedy=', 9, 'and mini =', 9)


In [124]:
!python CoinChange.py 31

('greedy=', 7, 'and mini =', 7)


In [125]:
a = 'abc'

In [126]:
a *= a

TypeError: can't multiply sequence by non-int of type 'str'

In [127]:
a * a

TypeError: can't multiply sequence by non-int of type 'str'

In [129]:
to_return =''
for letter in a:
    to_return += letter*2
    print(to_return)

aa
aabb
aabbcc


In [130]:
a = 1
b = 2

In [131]:
a, b = b, a

In [132]:
a

2

In [133]:
b

1

In [134]:
3%2

1

In [135]:
def func(int i){
 if(i%2) return 0;
 else return 1;
}

SyntaxError: invalid syntax (<ipython-input-135-2b59343f5ad2>, line 1)

In [140]:
if (5%2):
    print(3)

3


In [141]:
for num in range(2,101):    
   for i in range(2,num):  
       if (num % i) == 0:  
           break  
   else:  
       print(num)  

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [143]:
for num in range(2,101):
    if all(num%i!=0 for i in range(2,num)):
       print(num)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [146]:
import math
print(2)
for num in range(3,101,2):
    if all(num%i!=0 for i in range(3,int(math.sqrt(num))+1, 2)):
        print(num)

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97
